/******************************************************************************/
/* SCRIPT PADRÃO DE CONTROLE DE ACESSO E PERMISSÕES - FIREBIRD 3.0           */
/* Autor: José Luiz                                                            */
/******************************************************************************/

/* 1. TABELA DE PERFIS DE ACESSO */
CREATE TABLE PERFIL (
    ID_PERFIL INTEGER NOT NULL,
    NOME_PERFIL VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT PK_PERFIL PRIMARY KEY (ID_PERFIL)
);

/* 2. TABELA DE MÓDULOS / TELAS DO SISTEMA */
CREATE TABLE MODULO (
    ID_MODULO INTEGER NOT NULL,
    NOME_MODULO VARCHAR(50) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(100),
    CONSTRAINT PK_MODULO PRIMARY KEY (ID_MODULO)
);

/* 3. TABELA DE USUÁRIOS */
CREATE TABLE USUARIO (
    ID_USUARIO INTEGER NOT NULL,
    ID_PERFIL INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    LOGIN VARCHAR(30) NOT NULL UNIQUE,
    SENHA VARCHAR(64) NOT NULL, /* Hash SHA-256 */
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL)
);

/* 4. TABELA DE PERMISSÕES DO PERFIL POR MÓDULO */
CREATE TABLE PERMISSAO_PERFIL (
    ID_PERFIL INTEGER NOT NULL,
    ID_MODULO INTEGER NOT NULL,
    CAN_ACCESS CHAR(1) DEFAULT 'N' CHECK (CAN_ACCESS IN ('S', 'N')),
    CAN_INSERT CHAR(1) DEFAULT 'N' CHECK (CAN_INSERT IN ('S', 'N')),
    CAN_EDIT CHAR(1) DEFAULT 'N' CHECK (CAN_EDIT IN ('S', 'N')),
    CAN_DELETE CHAR(1) DEFAULT 'N' CHECK (CAN_DELETE IN ('S', 'N')),
    CONSTRAINT PK_PERMISSAO_PERFIL PRIMARY KEY (ID_PERFIL, ID_MODULO),
    CONSTRAINT FK_PERM_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL) ON DELETE CASCADE,
    CONSTRAINT FK_PERM_MOD_PERFIL FOREIGN KEY (ID_MODULO) REFERENCES MODULO(ID_MODULO) ON DELETE CASCADE
);

/* 5. TABELA DE PERMISSÕES DO PERFIL POR COMPONENTE ESPECÍFICO */
CREATE TABLE PERMISSAO_COMPONENTE (
    ID_PERFIL INTEGER NOT NULL,
    NOME_FORMULARIO VARCHAR(60) NOT NULL,
    NOME_COMPONENTE VARCHAR(60) NOT NULL,
    HABILITADO CHAR(1) DEFAULT 'S' CHECK (HABILITADO IN ('S', 'N')),
    VISIVEL CHAR(1) DEFAULT 'S' CHECK (VISIVEL IN ('S', 'N')),
    CONSTRAINT PK_PERMISSAO_COMPONENTE PRIMARY KEY (ID_PERFIL, NOME_FORMULARIO, NOME_COMPONENTE),
    CONSTRAINT FK_PERM_COMP_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL) ON DELETE CASCADE
);

/******************************************************************************/
/* SEQUENCES E TRIGGERS PARA AUTOINCREMENTO DE IDs                            */
/******************************************************************************/

CREATE SEQUENCE GEN_PERFIL_ID;
CREATE SEQUENCE GEN_MODULO_ID;
CREATE SEQUENCE GEN_USUARIO_ID;

SET TERM ^ ;

CREATE TRIGGER BI_PERFIL_ID FOR PERFIL
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_PERFIL IS NULL OR NEW.ID_PERFIL = 0) THEN
    NEW.ID_PERFIL = NEXT VALUE FOR GEN_PERFIL_ID;
END^

CREATE TRIGGER BI_MODULO_ID FOR MODULO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_MODULO IS NULL OR NEW.ID_MODULO = 0) THEN
    NEW.ID_MODULO = NEXT VALUE FOR GEN_MODULO_ID;
END^

CREATE TRIGGER BI_USUARIO_ID FOR USUARIO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_USUARIO IS NULL OR NEW.ID_USUARIO = 0) THEN
    NEW.ID_USUARIO = NEXT VALUE FOR GEN_USUARIO_ID;
END^

SET TERM ; ^

/******************************************************************************/
/* CARGA INICIAL DE DADOS                                                     */
/******************************************************************************/

/* Perfis padrão */
INSERT INTO PERFIL (ID_PERFIL, NOME_PERFIL) VALUES (1, 'ADMINISTRADOR');
INSERT INTO PERFIL (ID_PERFIL, NOME_PERFIL) VALUES (2, 'OPERADOR');

/* Usuário ADMIN Padrão (Senha inicial: 123456 em SHA-256) */
INSERT INTO USUARIO (ID_PERFIL, NOME, LOGIN, SENHA, ATIVO) 
VALUES (1, 'ADMINISTRADOR', 'ADMIN', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'S');